spring:
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://localhost:5432/social_media
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
jwt:
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJUpJv/bbRs54DGi+TaxroOG+0bwp2dxByUR4mWyHUi8jgI1cLnHiyF3/34vjHM+1YmSplHfCJLC/Z9MVh8AZ5sCAwEAAQ==
  issuer: honeymoney
  expirationMs: 600000
  refreshExpirationMs: 1200000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  override-with-generic-response: false